### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by janosimas** [joeroback/atom-clang#12]
When I try to  install the package I get this error:

```
> segfault-handler@1.0.0 install /tmp/apm-install-dir-1161011-1627-ix1hve/node_modules/atom-clang/node_modules/segfault-handler
> node-gyp rebuild

make: Entering directory `/tmp/apm-install-dir-1161011-1627-ix1hve/node_modules/atom-clang/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/obj.target/segfault-handler.node
  COPY Release/segfault-handler.node
make: Leaving directory `/tmp/apm-install-dir-1161011-1627-ix1hve/node_modules/atom-clang/node_modules/segfault-handler/build'

> atom-clang@1.0.13 install /tmp/apm-install-dir-1161011-1627-ix1hve/node_modules/atom-clang
> node-gyp rebuild


/bin/sh: 0: Illegal option --
gyp: Call to '--includedir' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-38-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-1161011-1627-ix1hve/node_modules/atom-clang
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1161011-1627-ix1hve/package.json'
npm WARN apm-install-dir-1161011-1627-ix1hve No description
npm WARN apm-install-dir-1161011-1627-ix1hve No repository field.
npm WARN apm-install-dir-1161011-1627-ix1hve No README data
npm WARN apm-install-dir-1161011-1627-ix1hve No license field.
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/jsimas/.atom/.apm/.apmrc" "--userconfig" "/home/jsimas/.atom/.apmrc" "install" "/tmp/d-1161011-1627-p79n93/package.tgz" "--runtime=electron" "--target=1.3.6" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-clang@1.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-clang@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-clang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-clang
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-clang
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1161011-1627-ix1hve/npm-debug.log
```

**Comment by joeroback** [comment]
it looks like it cannot find `llvm-config` executable. this package requires clang 3.8 or 3.9 to be installed and that the executable `llvm-config` to in `$PATH` environment variable before launching Atom (as the installer from within Atom will end up looking for `llvm-config`)

**Comment by janosimas** [comment]
I was using clang 3.6, with 3.8 it installed ok.
thanks
