### ISSUE TITLE
macOS Sierra Install error

### ISSUE THREAD

**Issue by eddyc** [joeroback/atom-clang#16]
Hi,
Tried to install in Atom 1.12.6, I get this error 

```
Installing “atom-clang@1.0.13” failed.Hide output…

> segfault-handler@1.0.0 install /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-1161112-29619-dp2we5/node_modules/atom-clang/node_modules/segfault-handler
> node-gyp rebuild

  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/segfault-handler.node

> atom-clang@1.0.13 install /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-1161112-29619-dp2we5/node_modules/atom-clang
> node-gyp rebuild


2016-12-12 09:38:20.029 xcodebuild[29631:162138] [MT] PluginLoading: Required plug-in compatibility UUID DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/JumpMarks.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-12-12 09:38:20.029 xcodebuild[29631:162138] [MT] PluginLoading: Required plug-in compatibility UUID DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-12-12 09:38:20.166 xcodebuild[29631:162138] WARNING: Failed to load plugin at path: "/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim): no suitable image found.  Did find:
	/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim: code signing blocked mmap() of '/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim'" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim, NSDebugDescription=dlopen_preflight(/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim): no suitable image found.  Did find:
	/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim: code signing blocked mmap() of '/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim', NSBundlePath=/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin, NSLocalizedDescription=The bundle “XVim” couldn’t be loaded because it is damaged or missing necessary resources.}
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
/bin/sh: --: invalid option
Usage:	/bin/sh [GNU long option] [option] ...
	/bin/sh [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--protected
	--rcfile
	--restricted
	--verbose
	--version
	--wordexp
Shell options:
	-irsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
gyp: Call to '--includedir' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-1161112-29619-dp2we5/node_modules/atom-clang
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-1161112-29619-dp2we5/package.json'
npm WARN apm-install-dir-1161112-29619-dp2we5 No description
npm WARN apm-install-dir-1161112-29619-dp2we5 No repository field.
npm WARN apm-install-dir-1161112-29619-dp2we5 No README data
npm WARN apm-install-dir-1161112-29619-dp2we5 No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/eddyc/.atom/.apm/.apmrc" "--userconfig" "/Users/eddyc/.atom/.apmrc" "install" "/private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/d-1161112-29619-1od2dkm/package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-clang@1.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-clang@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-clang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-clang
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-clang
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-1161112-29619-dp2we5/npm-debug.log

```

Just wondering if there are any suggestions on how I can fix this, or is this a Mac incompatibility issue.
Thanks
Ed

**Comment by joeroback** [comment]
you need to install clang 3.8 or clang 3.9 from llvm.org, MacPorts, or HomeBrew. It uses the `llvm-config` command to find the libraries, so llvm-config executable needs to be in your PATH, so that the Atom install process can correctly compile the node module.

Xcode's version of LLVM/CLANG does not ship with the required headers and libraries.

**Comment by eddyc** [comment]
Thanks for your help, I have installed that and it seems to have gotten further but still fails looking for cstdint.h which apparently doesn't exist in Mac OS


```
Installing atom-clang to /Users/eddyc/.atom/packages ✗

> segfault-handler@1.0.0 install /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-1161112-46353-1frh56w/node_modules/atom-clang/node_modules/segfault-handler
> node-gyp rebuild

  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/segfault-handler.node

> atom-clang@1.0.13 install /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-1161112-46353-1frh56w/node_modules/atom-clang
> node-gyp rebuild

  CXX(target) Release/obj.target/clang/src/clang_translationunit.o

2016-12-12 17:46:15.701 xcodebuild[46366:258166] [MT] PluginLoading: Required plug-in compatibility UUID DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/JumpMarks.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-12-12 17:46:15.702 xcodebuild[46366:258166] [MT] PluginLoading: Required plug-in compatibility UUID DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-12-12 17:46:15.824 xcodebuild[46366:258166] WARNING: Failed to load plugin at path: "/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim): no suitable image found.  Did find:
	/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim: code signing blocked mmap() of '/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim'" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim, NSDebugDescription=dlopen_preflight(/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim): no suitable image found.  Did find:
	/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim: code signing blocked mmap() of '/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim', NSBundlePath=/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin, NSLocalizedDescription=The bundle “XVim” couldn’t be loaded because it is damaged or missing necessary resources.}
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
2016-12-12 17:46:17.073 xcodebuild[46461:258394] [MT] PluginLoading: Required plug-in compatibility UUID DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/JumpMarks.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-12-12 17:46:17.074 xcodebuild[46461:258394] [MT] PluginLoading: Required plug-in compatibility UUID DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-12-12 17:46:17.193 xcodebuild[46461:258394] WARNING: Failed to load plugin at path: "/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim): no suitable image found.  Did find:
	/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim: code signing blocked mmap() of '/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim'" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim, NSDebugDescription=dlopen_preflight(/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim): no suitable image found.  Did find:
	/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim: code signing blocked mmap() of '/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim', NSBundlePath=/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin, NSLocalizedDescription=The bundle “XVim” couldn’t be loaded because it is damaged or missing necessary resources.}
../src/clang_translationunit.cpp:5:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^
1 error generated.
make: *** [Release/obj.target/clang/src/clang_translationunit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-1161112-46353-1frh56w/node_modules/atom-clang
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-1161112-46353-1frh56w/package.json'
npm WARN apm-install-dir-1161112-46353-1frh56w No description
npm WARN apm-install-dir-1161112-46353-1frh56w No repository field.
npm WARN apm-install-dir-1161112-46353-1frh56w No README data
npm WARN apm-install-dir-1161112-46353-1frh56w No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/eddyc/.atom/.apm/.apmrc" "--userconfig" "/Users/eddyc/.atom/.apmrc" "install" "/private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/d-1161112-46353-xjrp8l/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-clang@1.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-clang@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-clang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-clang
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-clang
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-1161112-46353-1frh56w/npm-debug.log

```

**Comment by joeroback** [comment]
I'll have to check this out later today, I am using macOS 10.12.1, but I am compiling with clang-3.9 from MacPorts, not Apple's compiler, since its riddled with complexities like this.

**Comment by eddyc** [comment]
It cool, think I fixed it, opened a new pull request

**Comment by joeroback** [comment]
fixed in https://github.com/joeroback/atom-clang/pull/18
