### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by kedwin** [joeroback/atom-clang#19]
> segfault-handler@1.0.0 install /tmp/apm-install-dir-11702-3702-58kb8x.cejliyhkt9/node_modules/atom-clang/node_modules/segfault-handler
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-11702-3702-58kb8x.cejliyhkt9/node_modules/atom-clang/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/obj.target/segfault-handler.node
  COPY Release/segfault-handler.node
make: Leaving directory '/tmp/apm-install-dir-11702-3702-58kb8x.cejliyhkt9/node_modules/atom-clang/node_modules/segfault-handler/build'

> atom-clang@1.0.14 install /tmp/apm-install-dir-11702-3702-58kb8x.cejliyhkt9/node_modules/atom-clang
> node-gyp rebuild

/bin/sh: --: invalid option
Usage:	/bin/sh [GNU long option] [option] ...
	/bin/sh [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--rcfile
	--restricted
	--verbose
	--version
Shell options:
	-ilrsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
gyp: Call to '--includedir' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.13-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11702-3702-58kb8x.cejliyhkt9/node_modules/atom-clang
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11702-3702-58kb8x.cejliyhkt9/package.json'
npm WARN apm-install-dir-11702-3702-58kb8x.cejliyhkt9 No description
npm WARN apm-install-dir-11702-3702-58kb8x.cejliyhkt9 No repository field.
npm WARN apm-install-dir-11702-3702-58kb8x.cejliyhkt9 No README data
npm WARN apm-install-dir-11702-3702-58kb8x.cejliyhkt9 No license field.
npm ERR! Linux 4.8.13-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/john/.atom/.apm/.apmrc" "--userconfig" "/home/john/.atom/.apmrc" "install" "/tmp/d-11702-3702-1a3xls4.1hkfwghkt9/package.tgz" "--runtime=electron" "--target=1.4.13" "--arch=x64" "--global-style"
npm ERR! node v7.3.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! atom-clang@1.0.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-clang@1.0.14 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-clang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-clang
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-clang
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11702-3702-58kb8x.cejliyhkt9/npm-debug.log

**Comment by kedwin** [comment]
i had to install llvm package
