### ISSUE TITLE
Failed to activate the atom-clang package

### ISSUE THREAD

**Issue by apostolos107** [joeroback/atom-clang#35]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [atom-clang](https://github.com/joeroback/atom-clang) package 1.0.14

### Stack Trace

Failed to activate the atom-clang package

```
At The module '/home/apostolos107/.atom/packages/atom-clang/build/Release/clang.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 49. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

Error: The module '/home/apostolos107/.atom/packages/atom-clang/build/Release/clang.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 49. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at bindings (/packages/atom-clang/node_modules/bindings/bindings.js:81:44)
    at /packages/atom-clang/lib/events.coffee:13:26)
    at /packages/atom-clang/lib/events.coffee:4:1)
    at /packages/atom-clang/lib/events.coffee:4:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-clang/index.coffee:10:10)
    at /packages/atom-clang/index.coffee:1:1)
    at /packages/atom-clang/index.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
```

### Commands

```
```

### Non-Core Packages

```
atom-clang 1.0.14 
atom-ignore 0.2.0 
autocomplete-clang 0.11.3 
autocomplete-java 1.2.7 
busy-signal 1.4.3 
intentions 1.1.5 
language-cup 1.1.2 
language-jflex 1.0.0 
linter 2.2.0 
linter-ui-default 1.6.8 
remote-edit 1.9.0 
teletype 0.1.2 
```

**Comment by joeroback** [comment]
unfortunately since this is a compiled package, you have to recompile it if Atom updates the underlying Electron/Node.. You should at least be able to do it in the GUI

![atom-rebuild](https://user-images.githubusercontent.com/156174/32966868-7780bcbc-cb98-11e7-957c-ec623c27e376.png)

**Comment by twdkeule** [comment]
There is no button in the GUI on Atom 1.28.0 

```
The module '/home/thomas/.atom/packages/atom-clang/build/Release/clang.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 54. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by twdkeule** [comment]
For future reference: the package can be rebuild by executing 
`node-gyp rebuild` in the package directory (`~/.atom/packages/atom-clang`)
