### ISSUE TITLE
Failed to load the atom-clang package

### ISSUE THREAD

**Issue by lrigazio** [joeroback/atom-clang#36]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [atom-clang](https://github.com/joeroback/atom-clang) package 1.0.14

### Stack Trace

Failed to load the atom-clang package

```
At Cannot find module 'segfault-handler'

Error: Cannot find module 'segfault-handler'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/luca/build/atom-clang/index.coffee:5:11)
    at Object.<anonymous> (/home/luca/build/atom-clang/index.coffee:1:1)
    at Object.<anonymous> (/home/luca/build/atom-clang/index.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:937:35)
    at /usr/share/atom/resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:618:16)
    at config.transact (/usr/share/atom/resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:529:23)
    at /usr/share/atom/resources/app/src/atom-environment.js:832:34
```

### Commands

```
```

### Non-Core Packages

```
atom-clang 1.0.14 
atom-clang-expand 0.1.3 
atom-debugger 0.1.6 
atom-updater-linux 0.1.4 
build 0.70.0 
busy-signal 1.4.3 
```

**Comment by RichOnLyne** [comment]
I'm getting the same, from around the same time.
Thought I'd better report it to as there's been no movement on this issue in a couple of months:

```
System + App:
Mac OS X: 10.10.3
Atom 1.24.0
```

```
packages: 
Ensime: 0.41.0
atom-clang: 1.0.14
browser-plus: 0.0.98
busy-signal: 1.4.3
formatter-json: 1.0.1
formatter: 2.12.4
git-control: 0.9.0
git-status: 0.3.4
hyperclick: 0.1.5
intentions: 1.1.5
js-beautify: 1.7.5
language-puppet: 0.23.0
language-scala: 1.1.9
language-terraform: 0.8.1
last-cursor-position: 0.9.2
linter-ui-default: 1.6.10
linter: 2.2.0
project-manager: 3.3.5
xml-formatter: 0.11.0
```

```
Error: Cannot find module 'segfault-handler'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/lyner/.atom/packages/atom-clang/index.coffee:5:11)
    at Object.<anonymous> (/Users/lyner/.atom/packages/atom-clang/index.coffee:1:1)
    at Object.<anonymous> (/Users/lyner/.atom/packages/atom-clang/index.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:818:27)
```

**Comment by joeroback** [comment]
hrmm. yea, basically Atom has gone the way of LSP and of course, `clangd` is still garbage. I don't have the time right now to make a competitor to `clangd`.. but I can try and fix up `atom-clang` to work with the latest Atom in the next couple of days.

LSP -> https://github.com/Microsoft/language-server-protocol
clangd -> https://clang.llvm.org/extra/clangd.html

Of course you still need a `clangd` -> lsp -> atom plugin, but its essentially a pass-through as all the smarts are supposed to be handled in `clangd`. In the long term, it would be nice for clang to support this officially, but right now `clangd` is such an alpha level its unusable for day-to-day work.

**Comment by joeroback** [comment]
pushed a new verssion that removes `segfault-handler` package
